import React from 'react';
import { Bot, Sparkles, Languages, CheckCircle2, BookmarkCheck, Cpu, FileCheck } from 'lucide-react';

export function ExecutiveNarrativeCard({ synthesisData }) {
  const synth = synthesisData || {};
  const summary = synth.executive_summary || "The proposed enterprise demonstrates sound financial and commercial feasibility with healthy debt coverage.";
  const recommendations = synth.strategic_recommendations || [];
  const bankNotes = synth.bank_appraisal_notes || "Enterprise satisfies credit underwriting benchmarks.";
  const lang = (synth.language || synth.target_language || "en").toUpperCase();
  const isFallback = synth.is_fallback ?? true;
  const isCached = synth.is_cached ?? false;
  const modelName = synth.model_name || (isFallback ? "deterministic_narrative_engine_v1.0" : "groq:llama-3.3-70b");
  const latencyMs = synth.latency_ms ?? 0;

  // Simple Markdown bold formatter for synthesis narrative
  const formatMarkdown = (text) => {
    if (!text) return null;
    const parts = text.split(/(\*\*.*?\*\*)/g);
    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i} className="text-white font-semibold">{part.slice(2, -2)}</strong>;
      }
      return part;
    });
  };

  const paragraphs = summary.split('\n\n').filter(Boolean);

  return (
    <div className="glass-panel p-6 border-l-4 border-cyan-500 space-y-4">
      
      {/* Header with Clear Source Badge Distinction */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-2 border-b border-slate-800/80">
        <div className="flex items-center gap-2.5">
          <span className="p-2 rounded-xl bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">
            {isFallback ? <FileCheck className="w-5 h-5 text-amber-400" /> : <Bot className="w-5 h-5 text-cyan-400" />}
          </span>
          <div>
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <span>Executive Feasibility & Credit Appraisal Synthesis</span>
            </h3>
            <p className="text-[11px] text-slate-400">
              {isFallback
                ? "Generated by Deterministic Domain Template Engine • Zero Financial Recalculation Invariant"
                : "Synthesized by Tier 3 Groq Cloud AI Model • Immutable Upstream Financial Constants"}
            </p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* Source Distinction Badge */}
          {isFallback ? (
            <span className="text-[11px] font-semibold px-2.5 py-1 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-300 flex items-center gap-1.5" title="Rule-based deterministic template based on statutory MSME guidelines">
              <span className="w-1.5 h-1.5 rounded-full bg-amber-400" />
              Predefined Domain Template
            </span>
          ) : (
            <span className="text-[11px] font-semibold px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 flex items-center gap-1.5" title="Live LLM generation via Groq Cloud">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
              AI Synthesized ({modelName})
            </span>
          )}

          {/* Language Badge */}
          <span className="text-[11px] font-semibold px-2.5 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 flex items-center gap-1.5">
            <Languages className="w-3.5 h-3.5" /> {lang}
          </span>

          {/* Model / Latency Badge */}
          <span className="text-[10px] font-mono px-2 py-1 rounded-full bg-slate-800/80 border border-slate-700 text-slate-400">
            {isCached ? "⚡ Cached (<1ms)" : `${latencyMs.toFixed(0)}ms`}
          </span>
        </div>
      </div>

      {/* Synthesis Narrative with Paragraph Formatting */}
      <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 text-sm text-slate-200 leading-relaxed space-y-3">
        {paragraphs.map((p, idx) => (
          <p key={idx} className="leading-relaxed">
            {formatMarkdown(p)}
          </p>
        ))}
      </div>

      {/* Strategic Action Points */}
      {recommendations.length > 0 && (
        <div className="space-y-2 pt-1">
          <div className="text-xs font-bold text-cyan-400 uppercase tracking-wider flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Strategic Recommendations & Growth Milestones:</span>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
            {recommendations.map((rec, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-slate-900/60 border border-slate-800 text-xs text-slate-300 flex items-start gap-2.5">
                <span className="w-5 h-5 rounded-full bg-cyan-500/20 text-cyan-300 font-bold flex items-center justify-center shrink-0 text-[11px]">
                  {idx + 1}
                </span>
                <span className="mt-0.5 leading-normal">{formatMarkdown(rec)}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Bank Credit Memorandum Notes */}
      <div className="p-3.5 rounded-xl bg-indigo-950/30 border border-indigo-500/20 text-xs text-slate-300 flex items-start gap-2.5">
        <BookmarkCheck className="w-4 h-4 text-indigo-400 shrink-0 mt-0.5" />
        <div className="leading-normal">
          <strong className="text-indigo-300 font-semibold">Bank Credit Appraisal Memorandum: </strong>
          <span>{formatMarkdown(bankNotes)}</span>
        </div>
      </div>

      {/* Grounded Data Source Lineage Tag */}
      <div className="text-[10px] text-slate-500 flex flex-wrap items-center justify-between gap-2 pt-1 border-t border-slate-800/60">
        <span>
          <strong className="text-slate-400">Data Source:</strong> {isFallback ? "Deterministic Statutory Narrative Matrix (deterministic_narrative_engine_v1.0)" : `Groq Cloud AI Model (${modelName})`}
        </span>
        <span className="font-mono text-slate-400">
          Source Type: {isFallback ? "Predefined Domain Template" : "AI Generated"}
        </span>
      </div>

    </div>
  );
}

